version: "3.3"
services:
  main:
    build: .
    command: "daphne -b 0.0.0.0 -p 8000 stopify_drive.asgi:application"
    ports:
      - "8000:8000"
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=kavinraj
      - POSTGRES_PASSWORD=askask
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
