# Generated by Django 3.1.7 on 2021-09-04 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tokens',
            name='access_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_tokens',
            name='refresh_token',
            field=models.CharField(default='kasd', max_length=150),
            preserve_default=False,
        ),
    ]
