# Generated by Django 3.1.7 on 2021-09-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210904_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tokens',
            name='access_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_tokens',
            name='refresh_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_tokens',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
