# Generated by Django 3.1.7 on 2022-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210912_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistId', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=150)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
