# Generated by Django 3.1.7 on 2022-03-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_playlisttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.CharField(max_length=500)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener', to='api.user_tokens')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.user_tokens')),
            ],
        ),
        migrations.DeleteModel(
            name='PlaylistToken',
        ),
    ]
