# Generated by Django 3.1.7 on 2022-03-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220325_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistid',
            old_name='listener',
            new_name='user_tokens',
        ),
        migrations.RemoveField(
            model_name='playlistid',
            name='owner',
        ),
    ]
