# Generated by Django 4.0.3 on 2022-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220325_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistid',
            name='username',
            field=models.CharField(default='kavinraj', max_length=150),
            preserve_default=False,
        ),
    ]
