# Generated by Django 3.1.7 on 2022-04-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_playlistid_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistId',
        ),
    ]
