# Generated by Django 3.1.7 on 2022-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='shared with me', max_length=150),
            preserve_default=False,
        ),
    ]
