name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
       version: v0.10.0
       platforms: linux/arm64
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker buildx build . --file Dockerfile --tag kavinraj007/drivify:latest
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: kavinraj007/drivify:latest
