 name: Docker
 on:
   push:
     branches: ['master']
 jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Publish changed images
         uses: dawidd6/action-docker-publish-changed@v3
         with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN }}
            platforms: linux/amd64,linux/arm64,linux/arm
            tag: latest
       
