name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: kavinraj007/drivify

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        architecture: arm64

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME .
        echo "::set-output name=image::$IMAGE_NAME"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      uses: docker/push-action@v1
      with:
        tags: "$IMAGE_NAME"
